version: "3"

services:
  redis:
    image: "redis:alpine"

  app:
    # image: "barronwei/stripe-se"
    build: .
    depends_on:
      - redis
    env_file:
      - sample.env
    ports:
      - "3000:3000"
